# Generated by Django 3.2.7 on 2021-10-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211020_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['dateCreation'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
